export const elements = {
    totalSum: document.querySelector(".total__sum-number"),
    totalSumCurrency: document.querySelector(".total__sum-currency"),
    changeCurrencyBtns: document.querySelector(".total__currency"),
    totalUAHBtn: document.querySelector(".total__uah"),
    totalEuroBtn: document.querySelector(".total__euro"),
    totalDollarBtn: document.querySelector(".total__dollar"),
    totalUAHValue: document.querySelector(".currency--uah .currency__sum"),
    totalEurosValue: document.querySelector(".currency--euro .currency__sum"),
    totalDollarsValue: document.querySelector(".currency--dollar .currency__sum"),
    activeTotalBtn: "total--active",
    incomes: ".incomes",
    expenses: ".expenses",
    incomesList: ".items--incomes",
    expensesList: ".items--expenses",
    itemName: ".item__name",
    itemValue: ".item__value",
    inputName: ".title__add-name",
    inputValue: ".title__add-value",
    inputCurrency: ".title__add-currency",
    itemEditName: ".item__edit-name",
    itemEditValue: ".item__edit-value",
    itemEditCurrency: ".item__edit-currency",
    itemEditFinishBtn: ".item__edit-finish",
    addValuesBtn: document.querySelectorAll(".btn-add"),
    addIncomeBtn: document.querySelector(".add--income"),
    addExpenseBtn: document.querySelector(".add--expense")
};